spring:
  application:
    name: SISTEMA-DE-GESTION-DE-CURSOS

  datasource:
    url: jdbc:mysql://localhost:3306/gestion_cursos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: juan_curso
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080